// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XenoFx.Database.CacheDb;

#nullable disable

namespace XenoFx.Database.CacheDb.Migrations;

[DbContext(typeof(CacheDbContext))]
[Migration("20260308121807_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

        modelBuilder.Entity("XenoFx.Database.CacheDb.Models.AssetPresenceInfo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<byte[]>("AssetId")
                    .IsRequired()
                    .HasColumnType("BLOB");

                b.Property<string>("NormalizedPath")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("OriginalPath")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<ulong>("StateIndex")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("NormalizedPath")
                    .IsUnique();

                b.ToTable("AssetPresences");
            });
#pragma warning restore 612, 618
    }
}
