<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSX.DotNet.Common\CSX.DotNet.Common.csproj" />
    <ProjectReference Include="..\CSX.DotNet.EFC.Common\CSX.DotNet.EFC.Common.csproj" />
    <ProjectReference Include="..\CSX.DotNet.Storage.AppProfiles\CSX.DotNet.Storage.AppProfiles.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Configuration\" />
  </ItemGroup>

</Project>
