<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.47.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSX.DotNet.Common\CSX.DotNet.Common.csproj" />
  </ItemGroup>

</Project>
