<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.40.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSX.DotNet.Common\CSX.DotNet.Common.csproj" />
  </ItemGroup>

</Project>
