using CSX.DotNet.Common.Data.Exceptions;
using CSX.DotNet.Common.Data.Text.Json;
using CSX.DotNet.Common.IO.Integrity.Strategies.IntegrityV1;
using CSX.DotNet.Common.Security.Net;
using HeyRed.Mime;
using System;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using XenoFx.Services.Processing.AssetIngestion.DTOs;

namespace XenoFx.Services.Processing.AssetIngestion;

public partial class AssetIngestionService
{
    // API

    public async Task<CachedAssetIndex> IngestFromUploadMetadataAsync(
        string uploadMetdataPath,
        CancellationToken ctoken = default)
    {
        string directory
            = Path.GetDirectoryName(uploadMetdataPath)
            ?? throw new InvalidOperationException($"Full path is expected. Unable to determine directory of {uploadMetdataPath}");

        AssetUploadMetadata metadata = await ReadMetadataAsync(uploadMetdataPath, ctoken);

        string pathToCacheFile = Path.Combine(
            directory,
            metadata.CachedFilename);

        return await IngestFromUploadMetadataAsync(
            metadata: metadata,
            pathToCacheFile: pathToCacheFile,
            ctoken: ctoken);
    }

    public async Task<CachedAssetIndex> IngestFromUploadMetadataAsync(
        AssetUploadMetadata metadata,
        string pathToCacheFile,
        CancellationToken ctoken = default)
    {
        CachedAssetIndex index = new()
        {
            TimeStamp = metadata.TimeStamp,
            CacheFilePath = pathToCacheFile,
        };

        // Map user claims when implemented

        // Metadata validation
        if (ExecutableGuard.IsExecutableMimeType(metadata.DeclaredMimeType) ||
            ExecutableGuard.IsExecutableFilename(metadata.DeclaredFilename))
            throw new UnsupportedFileTypeException("Forbidden or unsupported asset file format.");

        // Content validation
        await using (FileStream stream = File.OpenRead(pathToCacheFile))
        {
            // Ensure content isn't executable
            if (ExecutableGuard.IsExecutable(stream))
                throw new UnsupportedFileTypeException("Forbidden or unsupported asset file format.");

            // Validate the file type
            string extension = ValidateFormat(stream);
            if (!string.IsNullOrEmpty(extension))
                index.FileExtension = extension;
            else
                throw new UnsupportedFileTypeException("Forbidden or unsupported asset file format.");

            // Read integrity data
            var integrityDigest = await FileIntegrityV1.GetFullInfoV1Async(stream, ctoken);
            index.SHA256 = integrityDigest.SHA256;
            index.Blake3 = integrityDigest.Blake3;
            index.Crumbs = integrityDigest.Crumbs;

            // Other
            index.FileSize = stream.Length;
        }

        // Map metadata
        FileInfo fi = new(pathToCacheFile);
        index.FileModifiedAt = fi.LastWriteTimeUtc;
        index.FileCreatedAt = fi.CreationTimeUtc;
        index.FileMimeType = MimeTypesMap.GetMimeType(index.FileExtension);
        index.DeterminedFileName = metadata.DetermineFilename();

        // Map descriptive data
        index.Title = metadata.Title;

        // Attach non-standard properties here
        index.ExtraData = JsonObjectFactory
            // Deserialize or embed into a new JsonObject
            .NormalizeToJsonObject(metadata.ExtraData)
            // Attach additional context metadata (only if non-empty)
            .AttachPropertyWithCamelCasedName(nameof(metadata.PageUrl), metadata.PageUrl)
            .AttachPropertyWithCamelCasedName(nameof(metadata.DataUrl), metadata.DataUrl);

        // Do not assign AssetId and Location.
        // They need to be generated by the indexer.
        return index;
    }

    // Internal

    private static async Task<AssetUploadMetadata> ReadMetadataAsync(
        string uploadMetdataPath, CancellationToken ctoken)
    {
        await using FileStream fs = File.OpenRead(uploadMetdataPath);
        return await JsonSerializer.DeserializeAsync<AssetUploadMetadata>(
            utf8Json: fs,
            cancellationToken: ctoken)
            ?? throw new InvalidOperationException("Unknown metadata file format.");
    }
}