<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <Product>XenoServe</Product>
    <AssemblyTitle>XenoServe</AssemblyTitle>
    <Description>Core-functions server for XenoFX.</Description>
    <Version>0.$([System.DateTime]::UtcNow.ToString("yyyy.MMdd.HHmm"))</Version>

    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- SPA Proxy settings ~ Consider removing if it can't be fixed
  <PropertyGroup>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:5173</SpaProxyServerUrl>
    <SpaProxyDefaultUrl>/</SpaProxyDefaultUrl>
  </PropertyGroup>
  -->

  <!--References-->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
    <!--Needed For React-->
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="9.*-*" />
  </ItemGroup>

  <!--Projects-->
  <ItemGroup>
    <ProjectReference Include="..\CSX.DotNet.Modules.AuthIpPin\CSX.DotNet.Modules.AuthIpPin.csproj" />
    <ProjectReference Include="..\CSX.DotNet.Modules.FileUploader\CSX.DotNet.Modules.FileUploader.csproj" />
    <ProjectReference Include="..\XenoFx\XenoFx.csproj" />
    <ProjectReference Include="..\xenoserve.frontend\xenoserve.frontend.esproj" Condition="'$(IsPublish)' == 'true'">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <!-- Frontend build pipeline - Start -->
  <PropertyGroup>
    <SpaRoot>../xenoserve.frontend</SpaRoot>
    <WwwRoot>$(PublishDir)/wwwroot</WwwRoot>
    <SpaDist>$(SpaRoot)/dist/</SpaDist>
  </PropertyGroup>

  <!-- Copy React build artifacts into wwwroot -->
  <Target Name="CopyFrontendToWwwroot" AfterTargets="Publish">

    <!-- Clean while making allowances for legacy files -->
    <Message Text="Cleaning publish/wwwroot/... excluding /legacy" Importance="high" />
    <ItemGroup>
      <FilesToDelete Include="$(WwwRoot)/**/*.*" Exclude="$(WwwRoot)/legacy/**/*.*" />
      <DirsToDelete Include="$(WwwRoot)/**/" Exclude="$(WwwRoot)/legacy/" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" />
    <RemoveDir Directories="@(DirsToDelete)" />

    <!-- Finally copy SPA files to wwwroot -->
    <Message Text="Copying frontend build files to publish/wwwroot/..." Importance="high" />
    <ItemGroup>
      <FrontendFiles Include="$(SpaDist)**/*" />
    </ItemGroup>
    <MakeDir Directories="$(WwwRoot)" />
    <Copy SourceFiles="@(FrontendFiles)" DestinationFolder="$(WwwRoot)/%(RecursiveDir)" />
  </Target>
  <!-- Frontend build pipeline - End -->

  <!-- Exclude the data directories created when debugging -->
  <ItemGroup>
    <Compile Remove="Workspaces\**" />
    <Content Remove="Workspaces\**" />
    <EmbeddedResource Remove="Workspaces\**" />
    <None Remove="Workspaces\**" />
  </ItemGroup>
</Project>