<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <Product>XenoServe</Product>
    <AssemblyTitle>XenoServe</AssemblyTitle>
    <Description>Core-functions server for XenoFX.</Description>
    <Version>0.$([System.DateTime]::UtcNow.ToString("yyyy.MMdd.HHmm"))</Version>

    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="XenoServeWorkspace\**" />
    <Content Remove="XenoServeWorkspace\**" />
    <EmbeddedResource Remove="XenoServeWorkspace\**" />
    <None Remove="XenoServeWorkspace\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XenoFx\XenoFx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Api\Auth\" />
  </ItemGroup>

</Project>
