<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <Product>XenoFX</Product>
    <AssemblyTitle>XenoFX</AssemblyTitle>
    <Description>Core logic for XenoFramework.</Description>
    <Version>0.$([System.DateTime]::UtcNow.ToString("yyyy.MMdd.HHmm"))</Version>

    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\Control\**" />
    <EmbeddedResource Remove="Services\Control\**" />
    <None Remove="Services\Control\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.14.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSX.DotNet.Common.EFC\CSX.DotNet.Common.EFC.csproj" />
    <ProjectReference Include="..\CSX.DotNet.Common.IO.Integrity\CSX.DotNet.Common.IO.Integrity.csproj" />
    <ProjectReference Include="..\CSX.DotNet.Common\CSX.DotNet.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Processing\AssetMotionThumbnail\" />
  </ItemGroup>

</Project>
